<?php

declare(strict_types=1);

namespace Support\Minify;

use DateTimeImmutable;
use Stringable;
use function Support\datetime;

/**
 * Generated by a {@see \Support\Minify} class.
 *
 * Contains the minified string.
 *
 * @internal
 * @author Martin Nielsen
 */
final readonly class Output implements Stringable
{
    public DateTimeImmutable $timestamp;

    public Report $report;

    public function __construct(
        public ?string $key,
        public ?int    $fingerprint,
        public string  $string,
        ?int           $timestamp = null,
    ) {
        $this->timestamp = datetime( $timestamp ?? 'now' );
    }

    public function __toString() : string
    {
        return $this->string;
    }

    public function array() : array
    {
        return [
            'key'         => $this->key,
            'fingerprint' => $this->fingerprint,
            'string'      => $this->string,
            'timestamp'   => $this->timestamp->getTimestamp(),
        ];
    }
}
